apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-role-config
data:
  # This key 'roles.yaml' becomes the filename inside the container
  # Maps user to role. Groups are not supported in this demo
  roles.yaml: |
    roles:
      admin:
        - "admin"
        - "user1"
      user:
        - "user2"
        - "user3"
        - "user4"
        - "user5"
        